# Generated by Django 3.1.3 on 2020-12-29 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='SecureMessage',
        ),
    ]
